ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- [관리자 계정] member 계정 생성
CREATE USER oyj_member IDENTIFIED BY member1234;

-- [관리자 계정] CONNECT, RESOURCE + CREATE VIEW 권한 부여 + 객체 생성 공간 할당
GRANT CONNECT, RESOURCE, CREATE VIEW TO oyj_member;
ALTER USER oyj_member DEFAULT TABLESPACE SYSTEM QUOTA UNLIMITED ON SYSTEM;

-- oyj_member 계정 접속 방법 추가

-- [멤버 계정] 
-- 회원 테이블
CREATE TABLE MEMBER(
    MEMBER_NO NUMBER PRIMARY KEY,
    MEMBER_ID VARCHAR2(20) NOT NULL,
    MEMBER_PW VARCHAR2(20) NOT NULL,
    MEMBER_NM VARCHAR2(30) NOT NULL,
    MEMBER_GENDER CHAR(1) CHECK (MEMBER_GENDER IN ('M','F')),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    SECESSION_FL CHAR(1) DEFAULT 'N' CHECK (SECESSION_FL IN ('Y','N'))
);
COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호(PK)';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '회원 아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PW IS '회원 비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_NM IS '회원 이름';
COMMENT ON COLUMN MEMBER.MEMBER_GENDER IS '회원 성별(M/F)';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원 가입일';
COMMENT ON COLUMN MEMBER.SECESSION_FL IS '탈퇴여부(Y/N)';

-- 게시판 테이블
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE VARCHAR2(200) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    READ_COUNT NUMBER DEFAULT 0,
    MEMBER_NO NUMBER REFERENCES MEMBER -- MEMBER 테이블 PK 값 참조
);

COMMENT ON COLUMN BOARD.BOARD_NO IS '게시글 번호';
COMMENT ON COLUMN BOARD.BOARD_TITLE IS '게시글 제목';
COMMENT ON COLUMN BOARD.BOARD_CONTENT IS '게시글 내용';
COMMENT ON COLUMN BOARD.CREATE_DATE IS '게시글 작성일';
COMMENT ON COLUMN BOARD.READ_COUNT IS '조회수';
COMMENT ON COLUMN BOARD.MEMBER_NO IS '회원번호 (작성자)';


-- 댓글 테이블
CREATE TABLE REPLY (
    REPLY_NO NUMBER PRIMARY KEY,
    REPLY_CONTENT VARCHAR2(500) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    MEMBER_NO NUMBER REFERENCES MEMBER, -- MEMBER 테이블 PK 참조
    BOARD_NO NUMBER REFERENCES BOARD -- BOARD 테이블 PK 참조
);

COMMENT ON COLUMN REPLY.REPLY_NO IS '댓글 번호(PK)';
COMMENT ON COLUMN REPLY.REPLY_CONTENT IS '댓글 내용';
COMMENT ON COLUMN REPLY.CREATE_DATE IS '댓글 작성일';
COMMENT ON COLUMN REPLY.MEMBER_NO IS '회원번호(작성자)';
COMMENT ON COLUMN REPLY.BOARD_NO IS '게시글 번호(어떤 게시글의 댓글인지 확인)';


-- 각 테이블 PK 생성용 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO; -- 1부터 1씩 증가, 반복X
CREATE SEQUENCE SEQ_BOARD_NO;
CREATE SEQUENCE SEQ_REPLY_NO;

--------------------------------------------------------------------------------


-- 아이디 중복 검사
SELECT COUNT(*) FROM MEMBER
WHERE MEMBER_ID = 'user01'
AND SECESSION_FL = 'N'; -- 탈퇴 안 한 계정


-- 회원 가입
INSERT INTO MEMBER
VALUES(SEQ_MEMBER_NO.NEXTVAL, 'USER', 'PASS', '유저', 'F', DEFAULT, DEFAULT);

SELECT * FROM MEMBER;
COMMIT;

-- 로그인 
SELECT MEMBER_NO, MEMBER_ID, MEMBER_NM, MEMBER_GENDER, ENROLL_DATE
FROM MEMBER
WHERE MEMBER_ID = 'user'
AND MEMBER_PW = 'pass'
AND SECESSION_FL = 'N';

-- 가입된 회원 목록 조회(아이디, 이름, 가입일)
-- 단, 탈퇴한 회원 제외, 아이디 오름 차순 조회
SELECT MEMBER_ID, MEMBER_NM, ENROLL_DATE
FROM MEMBER
WHERE SECESSION_FL = 'N'
ORDER BY MEMBER_ID;

-- 내 정보 수정(이름, 성별)
UPDATE MEMBER SET
MEMBER_NM ='유저영',
MEMBER_GENDER = 'M'
WHERE MEMBER_NO = 1;

SELECT * FROM MEMBER;

ROLLBACK;

-- 비밀번호 변경
UPDATE MEMBER
SET MEMBER_PW = 'pass1'
WHERE MEMBER_NO = 1
AND MEMBER_PW = 'pass';

-- 회원 탈퇴
UPDATE MEMBER SET SECESSION_FL = 'Y'
WHERE MEMBER_NO = 1 AND MEMBER_PW = 'pass' ;

--------------------------------------------------------------------------------

-- 게시글 목록 조회
SELECT BOARD_NO, BOARD_TITLE, CREATE_DATE, READ_COUNT, MEMBER_NM
FROM BOARD
JOIN MEMBER USING (MEMBER_NO)
ORDER BY BOARD_NO DESC;
-- 게시글 번호가 크다 == 최신 글이다

-- 게시글 목록 조회 + 댓글 개수(상관 서브쿼리 + 스칼라 서브쿼리)
SELECT B.BOARD_NO, BOARD_TITLE, CREATE_DATE, READ_COUNT, MEMBER_NM, 
    (SELECT COUNT(*) 
     FROM REPLY A
     WHERE A.BOARD_NO = B.BOARD_NO) AS "댓글 개수"
FROM BOARD B
JOIN MEMBER USING(MEMBER_NO)
ORDER BY BOARD_NO DESC;

-- 댓글 개수 조회(특정 게시글만)
SELECT COUNT(*)
FROM REPLY
WHERE BOARD_NO = 10;

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글 1', '샘플1 내용입니다.', DEFAULT, DEFAULT, 1);

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글 2', '샘플2 내용입니다.', DEFAULT, DEFAULT, 1);

INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, '샘플 게시글 3', '샘플3 내용입니다.', DEFAULT, DEFAULT, 1);

COMMIT;

-- 댓글 샘플 데이터 삽입
-- REPLY_NO, REPLY_CONTENT, CREATE_DATE, MEMBER_NO, BOARD_NO
INSERT INTO REPLY
VALUES(SEQ_REPLY_NO.NEXTVAL, '샘플1의 댓글1', DEFAULT, 1, 10);

INSERT INTO REPLY
VALUES(SEQ_REPLY_NO.NEXTVAL, '샘플1의 댓글2', DEFAULT, 1, 10);

INSERT INTO REPLY
VALUES(SEQ_REPLY_NO.NEXTVAL, '샘플1의 댓글3', DEFAULT, 1, 10);

COMMIT;


-- 특정 게시글 상세 조회
SELECT B.* , MEMBER_NM
FROM BOARD B
JOIN MEMBER M ON(B.MEMBER_NO = M.MEMBER_NO)
WHERE BOARD_NO = 10;

-- 특정 게시글의 댓글 목록 조회
SELECT R.*, MEMBER_NM
FROM REPLY R
JOIN MEMBER M ON(R.MEMBER_NO = M.MEMBER_NO)
WHERE BOARD_NO = 10;

-- 게시글 수 증가
-- 이전 조회수 + 1
UPDATE BOARD
SET READ_COUNT = READ_COUNT + 1
WHERE BOARD_NO = 10;

ROLLBACK;

-- 게시글 삭제
DELETE FROM BOARD
WHERE BOARD_NO = 10;

-- 게시글 수정
ALTER TABLE BOARD
WHERE 

